# Generated by Django 4.2.6 on 2023-10-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="emp",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=80)),
                ("email", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=100)),
                ("sick_leave", models.IntegerField()),
                ("casual_leave", models.IntegerField()),
                ("annual_leave", models.IntegerField()),
                ("phone_number", models.IntegerField()),
                ("pid", models.IntegerField()),
                ("did", models.IntegerField()),
                ("manager_id", models.IntegerField()),
                ("status", models.BooleanField()),
                ("profile_url", models.CharField(max_length=30)),
            ],
        ),
    ]
