# Generated by Django 4.2.6 on 2023-10-27 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=80)),
                ("leader_id", models.IntegerField()),
            ],
            options={"verbose_name_plural": "Department",},
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=80)),
                ("email", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=100)),
                ("sick_leave", models.IntegerField()),
                ("casual_leave", models.IntegerField()),
                ("annual_leave", models.IntegerField()),
                ("phone_number", models.IntegerField()),
                ("status", models.BooleanField()),
                ("profile_url", models.CharField(max_length=30)),
                (
                    "did",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.department",
                    ),
                ),
                (
                    "manager_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.employee",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Employee",},
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("fed_by", models.IntegerField()),
                ("fed_to", models.IntegerField()),
                ("type", models.CharField(max_length=50)),
                ("fed_body", models.CharField(max_length=50)),
            ],
            options={"verbose_name_plural": "Feedback",},
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=80)),
                ("leader_id", models.IntegerField()),
                ("did", models.IntegerField()),
            ],
            options={"verbose_name_plural": "Project",},
        ),
        migrations.CreateModel(
            name="Requests",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("req_by", models.IntegerField()),
                ("req_to", models.IntegerField()),
                ("type", models.CharField(max_length=50)),
                ("req_body", models.CharField(max_length=50)),
            ],
            options={"verbose_name_plural": "Requests",},
        ),
        migrations.DeleteModel(name="emp",),
        migrations.AddField(
            model_name="employee",
            name="pid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="employee.project"
            ),
        ),
    ]
