# Generated by Django 4.2.6 on 2023-10-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_alter_feedback_fed_by_alter_feedback_fed_to_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="department", name="leader_id",),
        migrations.RemoveField(model_name="employee", name="manager_id",),
        migrations.RemoveField(model_name="project", name="leader_id",),
    ]
