# Generated by Django 4.2.6 on 2023-10-28 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_department_id_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='leader_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='leader_id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='did',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.project'),
        ),
    ]
