# Generated by Django 4.2.6 on 2023-10-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_remove_department_leader_id_remove_project_leader_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='3882f5e4-d0d9-440f-9d0b-2be33181ffd2', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='Employee', max_length=80),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='a5d1e028-1862-4ece-b4c6-33b14a4eccb0', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.CharField(default='92df0b05-cead-4b9f-9d7a-a7cbc82b267f', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default='5d807a72-a4ce-4a19-80bb-3d0ac664a76d', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requests',
            name='id',
            field=models.CharField(default='c2f52a19-a148-47b5-aef6-fc804fd2c4d5', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
