# Generated by Django 4.2.6 on 2023-10-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_department_id_alter_employee_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='f3abdc2a-84cf-4653-98c3-ec44fe34495f', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='56e5e2a3-9883-4da8-be42-a2ba4c76d560', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.CharField(default='7dbbcf8c-2671-4e71-8317-095e6a8a0ffa', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default='e0c5cdfd-9bb2-464d-ba64-c6f9ada47469', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requests',
            name='id',
            field=models.CharField(default='7a33cb27-2d98-40c1-a4de-c0b3bda6ff1a', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
