# Generated by Django 4.2.6 on 2023-10-30 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_department_id_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='askHR',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'askHR',
            },
        ),
        migrations.CreateModel(
            name='leaverequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('reason', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'leaverequest',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='hr_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='1402a138-12c9-470e-9ff2-eb323fafe267', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='6f235516-1b6b-4e1a-b8c8-108fa5594b2e', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default='dfe29a34-d47c-4c9d-9589-12edf7add097', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requests',
            name='id',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
