# Generated by Django 4.2.6 on 2023-10-30 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_askhr_leaverequest_employee_hr_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='askhr',
            name='hr_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='askhr',
            name='id',
            field=models.CharField(default='c6d04c4b-0293-4a56-b259-ae2d76bac4e8', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='06ac12f4-554a-4c84-8ee1-5c02a9368c75', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='c58e91c8-7a82-4028-9abb-06a10b2f2a0b', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.CharField(default='566fc0a4-ff10-4f81-8027-087fbdf7cd64', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='id',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default='87d764c6-7af6-41b0-ad10-4e266d1bbbec', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Requests',
        ),
    ]
